language: go

go:
  - 1.11.x
  - tip

compiler:
  - gcc

services:
  - mysql

before_install:
  - GO111MODULE=on go mod vendor
  - mysql -e "CREATE DATABASE IF NOT EXISTS cloudb;"
  - sudo mysql -e "grant all privileges on cloudb.* to testuser@'%' identified by '123456';FLUSH PRIVILEGES;"


script:
  - go build .
  - go test ./...  -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)